### ISSUE TITLE
Issue with database permissions 

### ISSUE THREAD

**Issue by karimcitoh** [PRINTR3D/formideos-client#84]
Sometimes, when launching formideos-client, printers database can not be read. 

```
Interface started on port 8080
07:02:26:620	 [core/utils/moduleManager.js]............."module formideos-interface activated"
+++++ printer +++++ 
new driver for printer: /dev/ttyUSB5
07:02:27:220	 [core/modules/printer/index.js]...........{"errno":-13,"code":"EACCES","path":"/home/pi/formideos/storage/database/printers"}

```

The repository was installed without using sudo and all permissions should be correct.
By changing the permissions of the "database" folder everything works. But this permissions will change later again, after doing setup or after adding printer.

**Comment by ChrisTerBeke** [comment]
Can't reproduce
