### ISSUE TITLE
Auto update slice profiles with new Katana version

### ISSUE THREAD

**Issue by karimcitoh** [PRINTR3D/formideos-client#90]
In drive are listed the latest changes that should be made in the slice profiles.

This document only shows changes in format. If you want to know more about the new functionality, more documentation will be added soon to the wiki!

**Comment by ChrisTerBeke** [comment]
Will do asap. same structure as done in the cloud using the reference file

**Comment by karimcitoh** [comment]
Can we not use the same file?

**Comment by ChrisTerBeke** [comment]
that's what I said ;) I'll get the latest reference file that fits the shipped katana binary for the client and add that to the repo

**Comment by ChrisTerBeke** [comment]
Or maybe you can update the file in the repo when you push a new katana binary to it

**Comment by karimcitoh** [comment]
Updating the file in the repo sounds like the best way of updating this file. So we can also visualize changes with commits

**Comment by ChrisTerBeke** [comment]
cool. I'll add the current file when I implement this and from there you can update it together with the binary.
